<b> Title: </b> Understanding Performance Dynamics in Modern Formula 1

<b> Topic: </b> Analysing the relationship between qualifying performance and race outcomes, intra-team competitive dynamics, and strategic tyre management using data from 2018 to 2024 from the datasource FastF1. 

<b> Research Question 1: </b>  Qualifying-Race Performance Correlation

<u> “What is the relationship between qualifying session performance metrics and final race standings across different circuits, seasons, and regulatory eras?” </u>

<u> <i> <center> 1a) Does the qualifying-race relationship change depending on the context of circuit type and overtaking difficulty? </center> </i> </u>

<u> <i> <center> 1b) Do the regulations affecting overtaking introduced in 2022 affect the qualifying-race correlation? </center> </i> </u>

This notebook studies the above questions using various statistical analyses, further detailed in the table of contents below. The aim of this notebook is to aid in producing a report that is well supported by data. We do this through consturcting two datasets, one for an elastic net multinomial logistic regression and another for a time series analysis which is implemented in R. 

Some of the <b> key outputs </b> of this report are descriptive EDA graphs, cross-validated model performance metrics, subgroup comparisons, and within-rice dependence summaries. For transparency, I have tried to thoroguhly explain and justify the use of each statistical tool within the notebook, but the overall conclusion and further discussion in implemented in the report that this notebook complements.

# insert table of contents here, need to fix formatting later. also table of outputs? to make it more professional
Including notes for my own clarity

1. Enivronment Setup // 1a) installing fastf1, turning off warnings, f1 cache enabling 1b) importing packages 1c) defining for reproducibility,  years we use in our data, year split 2022, how we define outcome (three classes), Qualifying and Race (Q and F).


2. Data Construction for question A // 
    2a) event-driver dataset for multinomial regression, whcih variables im stroting (variable table) and how i'm filtering, best qualifying time Q3 if exists else Q2 else Q1. merging data. derived labels (pre-2022, post 2022, circuit type(technical,non-tecnical etc), handling missing data, checking duplicates, total rows are comprehensible eda.  
    
3) EDA for q1A
    3a) class balance, qualifyig distrobution vs race finishing distribution, relationship plots, SPEARMAN Rank correlation, by circuit type and era etc. or is that q1b?
    
4) Analysis for q1A - Elastic net multinomial logistic regression
    4a) train test split, define seed and splits etc
    4b) preprocessing pipeline +SGD classifier
    4c) Cros validation for hyperparameter tuning and saving the best model
    4d) evaluation (accuracy, macro/weighted-f1, confusion matrix, classification report table. non-zero coeffs?
    4e) Subgroup eval? model performance by era (pre-2022). eval by circuitt type. add interaction terms?
    
5) results discussion. Furthermore, anoher way to evaluate can be looking at the lap by lap performance, using position as well whihc is dependent on qualifying performance

6) analysis within race time series (USING R)
....

    

extra, where does it belong?
defining seeds? train test splits? cv stuff.

Furthermore. I can use multinomial to look at both questions and then use time series to look at both questions a well. so divide the report into multinomial logistic and time series analysis.

# Introduction?
to the two question and overall?

# 1. Enivronment Setup
This is evrything that is necessary to run the code. 

#### FastF1
First is downloading the data itself which is very simple through !pip install. Then I ensure local caching so that the downloaded sessions are stored and reused to make the code efficient. I'm also turning off warnings for a cleaner output.

In [5]:
# !pip install fastf1

import fastf1

import os 
os.makedirs("fastf1_cache", exist_ok=True)
fastf1.Cache.enable_cache("fastf1_cache") # enabling cache locally

# ignoring warnings
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

#### Importing Packages
For this progect, I use <b>pandas</b> and <b>numpy</b> for data handling, <b>matplotlib</b> and <b>seaborn</b> for visualising, and <b>scikit-learn</b> for the multinomial model.

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["font.size"] = 11

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (accuracy_score, f1_score, classification_report, confusion_matrix)

#### Defining Variables Globally
From the very start, I want to be clearer about how we're processing the data. So for transparency, we're using the years 2018-2024. We chose 2024 because at the time of initial exploration, the 2025 session wasn't complete, and 2018 because the race style changes prior to the year, making analysis of those years unreliable. 

We further add a column to classify the years as pre-2022 and post-2022 to use for analysis of the regulation that was introduced in 2022. 

For race outcome, instead of just using the race finishing position from 1-20, we're doing it in categories for easier comparision. We decided on 3-class multinomial so first is positions 1-3 which we'll call "Podium", 4-10 as "Points", and 11-20 as "NoPoints". Another reason for this is smaple size per class, we want this to be more full which is why i've grouped classes together. changing this later, I think have it be 4-class (plus missing/dnf) is better with Winner, Podium, Points, NoPoints as the important classifications. 

We're using qualifying races and normal races which we'll denote the sessions as either "Q" for qualifying or "R". 

I'm also defining a random seed here to ensure reproducibility in the data splits and cross-validations.

In [3]:
# defining years in analysis
START_YEAR = 2018
END_YEAR = 2024
YEARS = list(range(START_YEAR, END_YEAR + 1))

ERA_SPLIT_YEAR = 2022 # when regulation was introduced

# defining ttype of session
QUALI_SESSION = "Q"
RACE_SESSION = "R"

# definign outcome function
def define_outcome(race_pos):
    if pd.isna(race_pos):
        return np.nan
    elif race_pos <= 3:
        return "Podium"
    elif race_pos <= 10:
        return "Points"
    else:
        return "NoPoints"
    
# setting random seed
RANDOM_SEED = 5
np.random.seed(RANDOM_SEED)

# 2. Data Construction

In this section, I derive the dataset used for my multinomial logistic regression model. In this, I have one row as the Year, Round, Event, Driver --> Qualifying Performance --> Race Outcome, as that is the necessary informaiton for the model. 

# BELOW IS CGBT

2a. Extracting Official Race Schedules (No Hard-Coded Rounds)

Rather than manually defining race rounds, I extract the official event schedule directly from FastF1 for each year. This ensures:

Only valid race weekends are included

No missing or cancelled rounds are mistakenly referenced

The dataset automatically adapts to different season lengths

In [6]:
def get_race_schedule(year):
    """
    Returns a filtered race schedule for a given year,
    including only official Grand Prix events with race sessions.
    """
    schedule = fastf1.get_event_schedule(year)
    
    # Keep only conventional race weekends
    schedule = schedule[schedule["EventFormat"].isin(["conventional", "sprint"])]
    
    # Keep only actual races (exclude testing)
    schedule = schedule[~schedule["EventName"].str.contains("Test", case=False)]
    
    schedule = schedule.reset_index(drop=True)
    
    return schedule


# Build master schedule for all years
all_schedules = []

for year in YEARS:
    schedule_year = get_race_schedule(year)
    schedule_year["Year"] = year
    all_schedules.append(schedule_year)

schedule_df = pd.concat(all_schedules, ignore_index=True)

print("Total events extracted:", len(schedule_df))
schedule_df.head()

Total events extracted: 137

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport,Year
0,1,Australia,Melbourne,FORMULA 1 2018 ROLEX AUSTRALIAN GRAND PRIX,2018-03-25,Australian Grand Prix,conventional,Practice 1,2018-03-23 12:00:00+11:00,2018-03-23 01:00:00,...,2018-03-24 14:00:00+11:00,2018-03-24 03:00:00,Qualifying,2018-03-24 17:00:00+11:00,2018-03-24 06:00:00,Race,2018-03-25 16:10:00+11:00,2018-03-25 05:10:00,True,2018
1,2,Bahrain,Sakhir,FORMULA 1 2018 GULF AIR BAHRAIN GRAND PRIX,2018-04-08,Bahrain Grand Prix,conventional,Practice 1,2018-04-06 14:00:00+03:00,2018-04-06 11:00:00,...,2018-04-07 15:00:00+03:00,2018-04-07 12:00:00,Qualifying,2018-04-07 18:00:00+03:00,2018-04-07 15:00:00,Race,2018-04-08 18:10:00+03:00,2018-04-08 15:10:00,True,2018
2,3,China,Shanghai,FORMULA 1 2018 HEINEKEN CHINESE GRAND PRIX,2018-04-15,Chinese Grand Prix,conventional,Practice 1,2018-04-13 10:00:00+08:00,2018-04-13 02:00:00,...,2018-04-14 11:00:00+08:00,2018-04-14 03:00:00,Qualifying,2018-04-14 14:00:00+08:00,2018-04-14 06:00:00,Race,2018-04-15 14:10:00+08:00,2018-04-15 06:10:00,True,2018
3,4,Azerbaijan,Baku,FORMULA 1 2018 AZERBAIJAN GRAND PRIX,2018-04-29,Azerbaijan Grand Prix,conventional,Practice 1,2018-04-27 13:00:00+04:00,2018-04-27 09:00:00,...,2018-04-28 14:00:00+04:00,2018-04-28 10:00:00,Qualifying,2018-04-28 17:00:00+04:00,2018-04-28 13:00:00,Race,2018-04-29 16:10:00+04:00,2018-04-29 12:10:00,True,2018
4,5,Spain,Barcelona,FORMULA 1 GRAN PREMIO DE ESPAÑA EMIRATES 2018,2018-05-13,Spanish Grand Prix,conventional,Practice 1,2018-05-11 11:00:00+02:00,2018-05-11 09:00:00,...,2018-05-12 12:00:00+02:00,2018-05-12 10:00:00,Qualifying,2018-05-12 15:00:00+02:00,2018-05-12 13:00:00,Race,2018-05-13 15:10:00+02:00,2018-05-13 13:10:00,True,2018

2b. Constructing the Event–Driver Dataset

In this section, I extract:

Qualifying session results (Q)

Race session results (R)

Merge them at the driver level

Add derived labels for:

<b>Era</b>

<b>Circuit Type</b>

<b>Race Outcome</b>

🏎️ Define Circuit Type Mapping (For Q1a)

Circuit types are grouped into broad categories reflecting overtaking difficulty.

You can refine this later if needed.


Circuits were categorised (PASSIVE) into Street, High-Speed, and Technical groups based on track layout characteristics (permanent vs temporary), average speed, and overtaking profile, using circuit guides from Formula1.com and FIA documentation. This grouping is an analytical simplification intended to proxy overtaking difficulty. should I make this into a different dataset and then import it?

In [18]:
# -------------------------------------------------------
# Circuit Type Mapping
# -------------------------------------------------------
# Categories:
# - "Street": narrow, limited overtaking (e.g., Monaco)
# - "HighSpeed": long straights / very fast layouts
# - "Technical": balanced permanent circuits (default)
# -------------------------------------------------------

CIRCUIT_TYPE_MAP = {

    # --- STREET ---
    "Monaco Grand Prix": "Street",
    "Singapore Grand Prix": "Street",
    "Azerbaijan Grand Prix": "Street",
    "Las Vegas Grand Prix": "Street",
    "Miami Grand Prix": "Street",
    "Australian Grand Prix": "Street",      # semi-street (Albert Park)
    "Canadian Grand Prix": "Street",        # semi-street (Gilles Villeneuve)

    # --- HIGH SPEED ---
    "Italian Grand Prix": "HighSpeed",
    "Belgian Grand Prix": "HighSpeed",
    "Saudi Arabian Grand Prix": "HighSpeed",
    "British Grand Prix": "HighSpeed",
    "Austrian Grand Prix": "HighSpeed",
    "Mexican Grand Prix": "HighSpeed",
    "São Paulo Grand Prix": "HighSpeed",
    "Brazilian Grand Prix": "HighSpeed",
    "Japanese Grand Prix": "HighSpeed",
    "Dutch Grand Prix": "HighSpeed",
    "Qatar Grand Prix": "HighSpeed",

    # --- TECHNICAL ---
    "Bahrain Grand Prix": "Technical",
    "Chinese Grand Prix": "Technical",
    "Spanish Grand Prix": "Technical",
    "Hungarian Grand Prix": "Technical",
    "French Grand Prix": "Technical",
    "German Grand Prix": "Technical",
    "United States Grand Prix": "Technical",
    "Emilia Romagna Grand Prix": "Technical",
    "Portuguese Grand Prix": "Technical",
    "Turkish Grand Prix": "Technical",
    "Abu Dhabi Grand Prix": "Technical"   # Yas Marina is permanent
}


def assign_circuit_type(event_name):
    """
    Assigns a circuit category based on event name.
    Defaults to 'Technical' if not found.
    """
    if isinstance(event_name, str):
        event_name = event_name.strip()
    return CIRCUIT_TYPE_MAP.get(event_name, "Technical")


print("Circuit type mapping defined correctly.")

Circuit type mapping defined correctly.

🏁 Extract Qualifying + Race Data Per Event

In [19]:
def get_event_driver_data(year, round_number, event_name):
    """
    Returns merged qualifying and race results for one event (one row per driver).

    Key design choice:
    - We load *only* what we need for results-level analysis.
      This dramatically reduces API calls and avoids hitting the 500 calls/hour limit.
    """
    try:
        # --- Load Qualifying (lightweight) ---
        quali = fastf1.get_session(year, round_number, QUALI_SESSION)
        quali.load(telemetry=False, laps=False, weather=False)

        # If results are missing, skip safely
        if quali.results is None or len(quali.results) == 0:
            print(f"Skipping {year} Round {round_number} ({event_name}): Qualifying results empty")
            return None

        q_results = quali.results.copy()

        # Best available qualifying time: Q3 if exists else Q2 else Q1
        q_results["QualiTime"] = (
            q_results["Q3"].fillna(q_results["Q2"]).fillna(q_results["Q1"])
        )

        q_keep = q_results[[
            "DriverNumber",
            "Abbreviation",
            "FullName",
            "TeamName",
            "Position",
            "Q1", "Q2", "Q3",   # keep raw sessions (optional but useful)
            "QualiTime"
        ]].rename(columns={"Position": "QualiPos"})

        # --- Load Race (lightweight) ---
        race = fastf1.get_session(year, round_number, RACE_SESSION)
        race.load(telemetry=False, laps=False, weather=False)

        if race.results is None or len(race.results) == 0:
            print(f"Skipping {year} Round {round_number} ({event_name}): Race results empty")
            return None

        r_results = race.results.copy()

        r_keep = r_results[[
            "DriverNumber",
            "Abbreviation",
            "Position",
            "GridPosition",
            "Status"
        ]].rename(columns={
            "Position": "RacePos",
            "GridPosition": "StartPos"
        })

        # --- Merge ---
        df = pd.merge(
            q_keep,
            r_keep,
            on=["DriverNumber", "Abbreviation"],
            how="inner"
        )

        # If merge drops everyone, skip (rare but can happen with weird identifiers)
        if len(df) == 0:
            print(f"Skipping {year} Round {round_number} ({event_name}): Merge produced 0 rows")
            return None

        # --- Add Metadata ---
        df["Year"] = year
        df["Round"] = round_number
        df["EventName"] = event_name

        # Era label
        df["Era"] = np.where(df["Year"] < ERA_SPLIT_YEAR, "Pre-2022", "Post-2022")

        # Circuit type
        df["CircuitType"] = df["EventName"].apply(assign_circuit_type)

        # Outcome (3-class)
        df["Outcome"] = df["RacePos"].apply(define_outcome)

        # Basic sanity: cast key positions to numeric (FastF1 often uses floats)
        for col in ["QualiPos", "RacePos", "StartPos"]:
            df[col] = pd.to_numeric(df[col], errors="coerce")

        return df

    except Exception as e:
        print(f"Skipping {year} Round {round_number} ({event_name}) due to error: {repr(e)}")
        return None

🔁 Loop Through All Events
My comment: there is an api limit of 500 per hour so you have to run the api several times across different hours. This is also why i'm extracting the minimum amount of information so it's minimal reruns. Using cache, I can store the information so I don't reuse the API calls on the same data. For reproducibility and anyone else who would like to check witht he data, I've saveed the loaded data into a csv so they don't have to go through the hassle of running the code multiple times to get the data.

In [27]:
event_driver_data = []

for idx, row in schedule_df.iterrows():
    year = row["Year"]
    round_number = row["RoundNumber"]
    event_name = row["EventName"]
    
    print(f"Processing {year} - Round {round_number} - {event_name}")
    
    df_event = get_event_driver_data(year, round_number, event_name)
    
    if df_event is not None:
        event_driver_data.append(df_event)

# Combine into final dataset
event_driver_df = pd.concat(event_driver_data, ignore_index=True)

print("\nFinal dataset shape:", event_driver_df.shape)
event_driver_df.head()

Processing 2018 - Round 1 - Australian Grand Prix

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '5', '33', '3', '20', '8', '27', '55', '77', '14', '2', '11', '18', '31', '28', '9', '16', '35', '10']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '7', '3', '14', '33', '27', '77', '2', '55', '11', '31', '16', '18', '28', '8', '20', '10', '9', '35']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 2 - Bahrain Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '7', '77', '44', '3', '10', '20', '27', '31', '55', '28', '11', '14', '2', '33', '8', '9', '35', '16', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '44', '10', '20', '27', '14', '2', '9', '31', '55', '16', '8', '18', '35', '11', '28', '7', '33', '3']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 3 - Chinese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '7', '77', '44', '33', '3', '27', '11', '55', '8', '20', '31', '14', '2', '28', '35', '10', '18', '16', '9']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '77', '7', '44', '33', '27', '14', '5', '55', '20', '31', '11', '2', '18', '35', '9', '8', '10', '16', '28']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 4 - Azerbaijan Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '77', '3', '33', '7', '31', '11', '27', '55', '18', '35', '14', '16', '20', '2', '10', '9', '28', '8']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '11', '5', '55', '16', '14', '18', '2', '28', '9', '10', '20', '77', '8', '33', '3', '27', '31', '35']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 5 - Spanish Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '7', '33', '3', '20', '14', '55', '8', '2', '10', '31', '16', '11', '27', '9', '35', '18', '28']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '3', '20', '55', '14', '11', '16', '18', '28', '9', '35', '2', '31', '7', '8', '10', '27']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 6 - Monaco Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '5', '44', '7', '77', '31', '14', '55', '11', '10', '27', '2', '35', '16', '8', '28', '9', '18', '20', '33']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '5', '44', '7', '77', '31', '10', '27', '33', '55', '9', '11', '20', '2', '8', '35', '18', '16', '28', '14']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 7 - Canadian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '33', '44', '7', '3', '27', '31', '55', '11', '20', '28', '16', '14', '2', '10', '18', '35', '9', '8']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '33', '3', '44', '7', '27', '55', '31', '16', '10', '8', '20', '11', '9', '2', '35', '14', '28', '18']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 8 - French Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '3', '7', '55', '16', '20', '8', '31', '27', '11', '10', '9', '14', '28', '2', '35', '18']
core           INFO 	Loading data for French Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '7', '3', '5', '20', '77', '55', '27', '16', '8', '2', '9', '28', '35', '14', '18', '11', '31', '10']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 9 - Austrian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '7', '33', '8', '3', '20', '55', '27', '31', '10', '16', '14', '18', '2', '11', '35', '28', '9']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '7', '5', '8', '20', '31', '11', '14', '16', '9', '10', '55', '35', '18', '2', '44', '28', '3', '77', '27']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 10 - British Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '7', '77', '33', '3', '20', '8', '16', '31', '27', '11', '14', '10', '9', '55', '2', '35', '18', '28']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '7', '77', '3', '27', '31', '14', '20', '11', '2', '18', '10', '35', '33', '8', '55', '9', '16', '28']
core           INFO 	Loading data for German Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 11 - German Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '7', '33', '20', '8', '27', '55', '16', '11', '14', '35', '9', '44', '3', '31', '10', '28', '18', '2']
core           INFO 	Loading data for German Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '7', '33', '27', '8', '11', '31', '9', '28', '20', '55', '2', '10', '16', '14', '18', '5', '35', '3']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 12 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '7', '5', '55', '10', '33', '28', '20', '8', '14', '3', '27', '9', '18', '2', '16', '31', '11', '35']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '7', '3', '77', '10', '20', '14', '55', '8', '28', '27', '31', '11', '9', '35', '18', '2', '33', '16']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 13 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '31', '11', '8', '7', '33', '3', '20', '77', '10', '28', '16', '9', '27', '55', '14', '35', '18', '2']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '33', '77', '11', '31', '8', '20', '10', '9', '55', '35', '18', '28', '2', '3', '7', '16', '14', '27']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 14 - Italian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['7', '5', '44', '77', '33', '8', '55', '31', '10', '18', '20', '35', '14', '27', '3', '11', '16', '28', '9', '2']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '77', '5', '33', '31', '11', '55', '18', '35', '16', '2', '27', '10', '9', '20', '3', '14', '28', '8']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 15 - Singapore Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '77', '7', '3', '11', '8', '31', '27', '14', '55', '16', '9', '10', '20', '28', '2', '35', '18']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '77', '7', '3', '14', '55', '16', '27', '9', '2', '10', '18', '8', '11', '28', '20', '35', '31']
core           INFO 	Loading data for Russian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 16 - Russian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '7', '20', '31', '16', '11', '8', '9', '33', '3', '10', '55', '27', '28', '14', '35', '2', '18']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '7', '33', '3', '16', '20', '31', '11', '8', '27', '9', '14', '18', '2', '55', '35', '10', '28']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 17 - Japanese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '7', '8', '28', '10', '31', '5', '11', '16', '20', '55', '18', '3', '27', '35', '14', '2', '9']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '3', '7', '5', '11', '8', '31', '55', '10', '9', '28', '14', '2', '35', '18', '16', '27', '20']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 18 - United States Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '7', '77', '3', '31', '27', '8', '16', '11', '55', '20', '10', '28', '33', '14', '35', '18', '9', '2']
core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['7', '33', '44', '5', '77', '27', '55', '11', '28', '9', '2', '10', '35', '18', '16', '3', '8', '14', '31', '20']
core           INFO 	Loading data for Mexican Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 19 - Mexican Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '33', '44', '5', '77', '7', '27', '55', '16', '9', '31', '14', '11', '28', '10', '8', '2', '20', '18', '35']
core           INFO 	Loading data for Mexican Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '5', '7', '44', '77', '27', '16', '2', '9', '10', '31', '18', '35', '28', '20', '8', '3', '11', '55', '14']
core           INFO 	Loading data for Brazilian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 20 - Brazilian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '7', '33', '3', '9', '16', '8', '10', '20', '11', '31', '27', '35', '55', '28', '14', '18', '2']
core           INFO 	Loading data for Brazilian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '7', '3', '77', '5', '16', '8', '20', '11', '28', '55', '10', '2', '31', '35', '14', '18', '27', '9']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2018 - Round 21 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '7', '3', '33', '8', '16', '31', '27', '55', '9', '20', '11', '14', '28', '10', '2', '35', '18']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '33', '3', '77', '55', '16', '11', '8', '20', '14', '28', '18', '2', '35', '10', '31', '9', '7', '27']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 1 - Australian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '16', '8', '20', '4', '7', '11', '27', '3', '23', '99', '26', '18', '10', '55', '63', '88']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '5', '16', '20', '27', '7', '18', '26', '10', '4', '11', '23', '99', '63', '88', '8', '3', '55']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 2 - Bahrain Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '5', '44', '77', '33', '20', '55', '8', '7', '4', '3', '23', '10', '11', '26', '99', '27', '18', '63', '88']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '4', '7', '10', '23', '11', '99', '26', '20', '18', '63', '88', '27', '3', '55', '8']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 3 - Chinese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '16', '33', '10', '3', '27', '20', '8', '26', '11', '7', '55', '4', '18', '63', '88', '23', '99']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '16', '10', '3', '11', '7', '23', '8', '18', '20', '55', '99', '63', '88', '4', '26', '27']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 4 - Azerbaijan Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '11', '26', '4', '99', '16', '55', '3', '23', '20', '18', '8', '27', '63', '88', '7', '10']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '16', '11', '55', '4', '18', '7', '23', '99', '20', '27', '63', '88', '10', '8', '26', '3']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 5 - Spanish Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '16', '10', '8', '20', '26', '3', '4', '23', '55', '7', '11', '27', '18', '99', '63', '88']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '16', '10', '20', '55', '26', '8', '23', '3', '27', '7', '11', '99', '63', '88', '18', '4']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 6 - Monaco Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '10', '20', '3', '26', '55', '23', '27', '4', '8', '7', '99', '16', '11', '18', '63', '88']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '33', '10', '55', '26', '23', '3', '8', '4', '11', '27', '20', '63', '18', '7', '88', '99', '16']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 7 - Canadian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '16', '3', '10', '77', '27', '4', '55', '20', '33', '26', '99', '23', '8', '11', '7', '18', '63', '88']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '16', '77', '33', '3', '27', '10', '18', '26', '55', '11', '99', '8', '7', '63', '20', '88', '23', '4']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 8 - French Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '4', '55', '5', '3', '10', '99', '23', '7', '27', '11', '20', '26', '8', '18', '63', '88']
core           INFO 	Loading data for French Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '55', '7', '27', '4', '10', '3', '11', '18', '26', '23', '99', '20', '88', '63', '8']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 9 - Austrian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '33', '77', '20', '4', '7', '99', '10', '5', '8', '27', '23', '3', '55', '11', '18', '26', '63', '88']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '16', '77', '5', '44', '4', '10', '55', '7', '99', '11', '3', '27', '18', '23', '8', '26', '63', '20', '88']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 10 - British Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '16', '33', '10', '5', '3', '4', '23', '27', '99', '7', '55', '8', '11', '20', '26', '18', '63', '88']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '10', '33', '55', '3', '7', '26', '27', '4', '23', '18', '63', '88', '5', '11', '99', '8', '20']
core           INFO 	Loading data for German Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 11 - German Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '10', '7', '8', '55', '11', '27', '16', '99', '20', '3', '26', '18', '4', '23', '63', '88', '5']
core           INFO 	Loading data for German Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '5', '26', '18', '55', '23', '8', '20', '44', '88', '63', '7', '99', '10', '77', '27', '16', '4', '3', '11']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 12 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '44', '16', '5', '10', '4', '55', '8', '7', '27', '23', '26', '99', '20', '63', '11', '3', '18', '88']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '16', '55', '10', '7', '77', '4', '23', '11', '27', '20', '3', '26', '63', '18', '99', '88', '8']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 13 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '5', '44', '77', '33', '3', '27', '7', '11', '20', '8', '4', '18', '23', '99', '10', '55', '26', '63', '88']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '77', '5', '23', '11', '26', '27', '10', '18', '4', '20', '8', '3', '63', '7', '88', '99', '55', '33']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 14 - Italian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '77', '5', '3', '27', '55', '23', '18', '7', '99', '20', '26', '4', '10', '8', '11', '63', '88', '33']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/14/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/14/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '77', '44', '3', '27', '23', '11', '33', '99', '4', '10', '18', '5', '63', '7', '8', '88', '20', '26', '55']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 15 - Singapore Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2019/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/15/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '5', '33', '77', '23', '55', '27', '4', '11', '99', '10', '7', '20', '26', '18', '8', '63', '88', '3']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/15/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/15/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '16', '33', '44', '77', '23', '4', '10', '27', '99', '8', '55', '18', '3', '26', '88', '20', '7', '11', '63']
core           INFO 	Loading data for Russian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 16 - Russian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2019/16/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/16/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '5', '33', '77', '55', '27', '4', '8', '3', '10', '11', '99', '20', '18', '7', '63', '88', '23', '26']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/16/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/16/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '23', '55', '11', '4', '20', '27', '18', '26', '7', '10', '99', '88', '63', '5', '3', '8']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/17/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/17/qualifying.json

Processing 2019 - Round 17 - Japanese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '16', '77', '44', '33', '23', '55', '4', '10', '8', '99', '18', '7', '26', '27', '3', '11', '63', '20', '88']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '5', '44', '23', '55', '16', '10', '11', '18', '26', '4', '7', '8', '99', '20', '63', '88', '33', '3', '27']
core           INFO 	Loading data for Mexican Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/18/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/18/qualifying.json

Processing 2019 - Round 18 - Mexican Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '16', '5', '44', '23', '77', '55', '4', '26', '10', '11', '27', '3', '7', '99', '18', '20', '8', '63', '88']
core           INFO 	Loading data for Mexican Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/18/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/18/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '16', '23', '33', '11', '3', '10', '27', '26', '18', '55', '99', '20', '63', '8', '88', '7', '4']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2019 - Round 19 - United States Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2019/19/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/19/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '5', '33', '16', '44', '23', '55', '4', '3', '10', '27', '20', '26', '18', '8', '99', '7', '63', '11', '88']
core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '5', '33', '16', '44', '23', '55', '4', '3', '10', '27', '20', '26', '18', '8', '99', '7', '63', '88', '11']
core           INFO 	Loading data for Brazilian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2019 - Round 20 - Brazilian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '16', '5', '23', '77', '26', '99', '4', '55', '7', '10', '27', '20', '3', '8', '11', '18', '63', '88']
core           INFO 	Loading data for Brazilian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2019/20/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2019/20/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '10', '55', '7', '99', '3', '44', '4', '11', '26', '20', '63', '8', '23', '27', '88', '5', '16', '18', '77']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2019 - Round 21 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '23', '5', '16', '11', '3', '55', '10', '8', '26', '4', '20', '18', '7', '27', '99', '63', '88']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '16', '5', '23', '4', '3', '55', '27', '11', '10', '18', '26', '20', '8', '99', '7', '63', '88', '77']

Processing 2020 - Round 1 - Austrian Grand Prix

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/1/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/1/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '4', '23', '11', '16', '55', '18', '3', '5', '10', '26', '31', '8', '20', '63', '99', '7', '6']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '4', '23', '44', '11', '16', '55', '18', '3', '5', '10', '26', '31', '8', '20', '63', '99', '7', '6']
core           INFO 	Loading data for Styrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2020 - Round 2 - Styrian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '55', '77', '31', '4', '23', '10', '3', '5', '16', '63', '18', '26', '20', '7', '11', '6', '99', '8']
core           INFO 	Loading data for Styrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/2/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/2/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '23', '4', '11', '18', '3', '55', '26', '7', '20', '8', '99', '10', '63', '6', '31', '16', '5']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '11', '16', '18', '33', '4', '5', '10', '3', '55', '23', '31', '63', '8', '20', '26', '99', '7', '6']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2020 - Round 3 - Hungarian Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['31', '44', '77', '18', '11', '5', '16', '33', '4', '55', '10', '3', '63', '23', '6', '20', '26', '8', '99', '7']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/4/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/4/qualifying.json

Processing 2020 - Round 4 - British Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '4', '18', '55', '3', '31', '5', '10', '23', '27', '26', '63', '20', '99', '7', '8', '6']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '4', '18', '55', '3', '31', '5', '10', '23', '27', '20', '99', '7', '8', '6', '26', '63']
core           INFO 	Loading data for 70th Anniversary Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '4', '27', '18', '16', '33', '23', '31', '55', '10', '26', '5', '3', '8', '6', '63', '99', '7', '20']
core           INFO 	Loading data for 70th Anniversary Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2020 - Round 5 - 70th Anniversary Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2020/5/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/5/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '16', '23', '18', '27', '31', '4', '26', '10', '5', '55', '3', '7', '8', '99', '63', '6', '20']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/6/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/6/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '11', '18', '23', '55', '4', '16', '10', '5', '26', '3', '7', '31', '20', '8', '63', '6', '99']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2020 - Round 6 - Spanish Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '11', '18', '23', '55', '4', '16', '10', '5', '26', '3', '7', '31', '20', '8', '63', '6', '99']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/7/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/7/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '3', '23', '31', '55', '11', '18', '4', '26', '10', '16', '5', '63', '7', '8', '99', '6', '20']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2020 - Round 7 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '3', '31', '23', '4', '10', '18', '11', '26', '7', '5', '16', '8', '6', '20', '99', '63', '55']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/8/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/8/qualifying.json

Processing 2020 - Round 8 - Italian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '55', '11', '33', '4', '3', '18', '23', '10', '26', '31', '16', '7', '20', '8', '5', '99', '63', '6']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '55', '11', '33', '4', '3', '18', '23', '10', '26', '31', '16', '7', '20', '8', '5', '99', '63', '6']
core           INFO 	Loading data for Tuscan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2020 - Round 9 - Tuscan Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '44', '18', '10', '11', '16', '23', '26', '8', '31', '55', '99', '7', '20', '6', '3', '5', '4', '63']
core           INFO 	Loading data for Tuscan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/9/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/9/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '23', '3', '11', '4', '26', '16', '7', '5', '63', '8', '18', '31', '6', '20', '99', '55', '33', '10']
core           INFO 	Loading data for Russian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '55', '31', '11', '33', '5', '18', '26', '3', '10', '16', '63', '8', '6', '20', '99', '7', '23', '4']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.7.0]

Processing 2020 - Round 10 - Russian Grand Prix

req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/10/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/10/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '44', '11', '3', '16', '31', '26', '10', '23', '99', '20', '5', '7', '4', '6', '8', '63', '55', '18']
core           INFO 	Loading data for Eifel Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '16', '33', '5', '4', '11', '3', '23', '10', '31', '26', '55', '7', '8', '20', '63', '99', '6', '27']

Processing 2020 - Round 11 - Eifel Grand Prix

core           INFO 	Loading data for Eifel Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/11/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/11/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '3', '11', '55', '10', '16', '27', '8', '99', '5', '7', '20', '6', '26', '4', '23', '31', '77', '63']
core           INFO 	Loading data for Portuguese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/12/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/12/qualifying.json

Processing 2020 - Round 12 - Portuguese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '11', '23', '55', '4', '10', '3', '31', '18', '26', '63', '5', '7', '99', '8', '20', '6']
core           INFO 	Loading data for Portuguese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '11', '23', '55', '4', '10', '3', '31', '18', '26', '63', '5', '7', '99', '8', '20', '6']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2020 - Round 13 - Emilia Romagna Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '10', '16', '3', '31', '26', '23', '18', '11', '5', '8', '55', '99', '4', '7', '63', '20', '6']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '3', '26', '16', '11', '55', '4', '7', '99', '6', '5', '18', '8', '23', '63', '33', '20', '31', '10']
core           INFO 	Loading data for Turkish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2020 - Round 14 - Turkish Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '16', '23', '31', '4', '5', '11', '77', '20', '18', '3', '55', '99', '10', '8', '7', '26', '63', '6', '44']
core           INFO 	Loading data for Turkish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['18', '33', '11', '23', '3', '44', '31', '7', '77', '99', '5', '16', '20', '4', '55', '26', '8', '6', '10', '63']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/15/qualifying.json

Processing 2020 - Round 15 - Bahrain Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '23', '11', '3', '31', '10', '4', '26', '5', '16', '18', '63', '55', '99', '7', '20', '8', '6']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '23', '11', '3', '31', '10', '4', '26', '5', '16', '18', '63', '55', '99', '7', '20', '8', '6']
core           INFO 	Loading data for Sakhir Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/16/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/16/qualifying.json

Processing 2020 - Round 16 - Sakhir Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '63', '33', '16', '11', '26', '3', '55', '10', '18', '31', '23', '5', '99', '4', '20', '6', '89', '7', '51']
core           INFO 	Loading data for Sakhir Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '63', '33', '16', '11', '26', '3', '55', '10', '18', '31', '23', '5', '99', '20', '6', '89', '7', '4', '51']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2020 - Round 17 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '23', '3', '31', '4', '44', '18', '55', '77', '11', '26', '16', '10', '5', '63', '99', '7', '20', '6', '51']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2020/17/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2020/17/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '44', '23', '4', '55', '3', '10', '31', '18', '26', '7', '16', '5', '63', '99', '6', '20', '51', '11']

Processing 2021 - Round 1 - Bahrain Grand Prix

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '10', '77', '11', '55', '7', '31', '18', '3', '16', '99', '22', '5', '14', '4', '63', '47', '9', '6']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '16', '10', '3', '4', '55', '14', '18', '11', '99', '22', '7', '63', '31', '6', '47', '9', '5']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '11', '33', '16', '10', '3', '4', '77', '31', '18', '55', '63', '5', '6', '14', '7', '99', '47', '9', '22']

Processing 2021 - Round 2 - Emilia Romagna Grand Prix

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '11', '33', '16', '10', '3', '4', '77', '31', '18', '55', '63', '5', '6', '14', '7', '99', '47', '9', '22']
core           INFO 	Loading data for Portuguese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 3 - Portuguese Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2021/3/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/3/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '11', '55', '31', '4', '16', '10', '5', '63', '99', '14', '22', '7', '3', '18', '6', '47', '9']
core           INFO 	Loading data for Portuguese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '11', '55', '31', '4', '16', '10', '5', '63', '99', '14', '22', '7', '3', '18', '6', '47', '9']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '16', '55', '77', '4', '10', '3', '7', '11', '14', '22', '31', '18', '63', '99', '5', '6', '47', '9']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 4 - Spanish Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2021/4/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/4/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '16', '11', '3', '55', '4', '31', '10', '18', '7', '5', '63', '99', '6', '14', '47', '9', '22']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '55', '16', '77', '11', '4', '44', '7', '10', '5', '99', '18', '3', '47', '14', '9', '63', '6', '22', '31']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 5 - Monaco Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '33', '77', '55', '4', '10', '44', '5', '11', '99', '31', '3', '18', '7', '63', '22', '14', '6', '9', '47']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/6/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/6/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '33', '10', '55', '4', '11', '22', '14', '77', '5', '31', '3', '7', '63', '6', '47', '9', '18', '99']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 6 - Azerbaijan Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '33', '10', '55', '11', '22', '14', '4', '77', '5', '31', '3', '7', '63', '6', '47', '9', '18', '99']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '55', '11', '44', '4', '14', '31', '10', '3', '16', '99', '18', '5', '7', '63', '22', '6', '47', '9']
core           INFO 	Loading data for French Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 7 - French Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '77', '4', '3', '10', '14', '5', '18', '55', '63', '22', '31', '99', '16', '7', '6', '47', '9']
core           INFO 	Loading data for Styrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '11', '22', '10', '16', '14', '18', '5', '99', '31', '55', '63', '7', '47', '3', '6', '4', '9']
core           INFO 	Loading data for Styrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 8 - Styrian Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '4', '11', '77', '10', '16', '14', '18', '63', '22', '55', '3', '5', '99', '6', '31', '7', '47', '9']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/9/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/9/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '4', '11', '44', '77', '10', '22', '5', '63', '18', '55', '16', '3', '14', '99', '7', '31', '6', '47', '9']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 9 - Austrian Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '4', '11', '44', '77', '10', '22', '63', '18', '55', '5', '16', '3', '14', '99', '7', '31', '6', '47', '9']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 10 - British Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '4', '5', '6', '7', '9', '10', '11', '14', '16', '18', '22', '31', '33', '44', '47', '55', '63', '77', '99']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/10/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/10/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '16', '77', '4', '3', '55', '14', '18', '31', '22', '10', '63', '99', '6', '7', '11', '9', '47', '5', '33']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2021 - Round 11 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '55', '16', '4', '11', '3', '14', '18', '10', '31', '5', '22', '7', '63', '6', '99', '47', '9']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/11/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/11/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['31', '44', '55', '14', '10', '22', '6', '63', '33', '7', '3', '47', '99', '9', '4', '77', '11', '16', '18', '5']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/12/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/12/qualifying.json

Processing 2021 - Round 12 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '63', '44', '3', '5', '10', '11', '77', '31', '4', '16', '6', '55', '14', '18', '99', '22', '47', '7', '9']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '63', '44', '3', '5', '10', '11', '31', '16', '6', '55', '14', '77', '99', '4', '22', '47', '9', '18', '7']
core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2021 - Round 13 - Dutch Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '44', '11', '14', '4', '18', '5', '16', '10', '3', '6', '31', '63', '99', '55', '22', '9', '88', '47']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '10', '16', '14', '55', '11', '31', '4', '3', '18', '5', '99', '88', '6', '63', '47', '22', '9']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '4', '5', '6', '9', '10', '11', '14', '16', '18', '22', '31', '33', '44', '47', '55', '63', '77', '88', '99']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 14 - Italian Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '3', '4', '44', '16', '55', '99', '11', '18', '14', '5', '31', '6', '63', '22', '9', '88', '47', '77', '10']
core           INFO 	Loading data for Russian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/15/qualifying.json

Processing 2021 - Round 15 - Russian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '63', '44', '3', '14', '77', '18', '11', '31', '5', '10', '22', '6', '16', '7', '47', '99', '9', '33']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '63', '44', '3', '14', '18', '11', '31', '5', '10', '22', '7', '47', '9', '77', '99', '6', '16', '33']
core           INFO 	Loading data for Turkish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/16/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/16/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '10', '14', '11', '4', '18', '22', '5', '31', '63', '47', '55', '3', '6', '99', '7', '9']

Processing 2021 - Round 16 - Turkish Grand Prix

core           INFO 	Loading data for Turkish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '16', '10', '14', '11', '4', '18', '22', '5', '44', '31', '63', '47', '6', '99', '7', '9', '55', '3']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '55', '33', '4', '77', '44', '3', '10', '16', '31', '5', '63', '7', '6', '99', '18', '14', '22', '47', '9']
core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 17 - United States Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2021/17/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/17/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '16', '3', '77', '55', '4', '22', '5', '99', '18', '7', '63', '6', '47', '9', '14', '31', '10']
core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/18/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/18/qualifying.json

Processing 2021 - Round 18 - Mexico City Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '11', '10', '55', '3', '16', '22', '4', '5', '7', '63', '99', '31', '14', '6', '47', '9', '18']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '11', '10', '55', '3', '16', '5', '7', '99', '14', '6', '47', '9', '63', '22', '4', '31', '18']
core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['3', '4', '5', '6', '7', '9', '10', '11', '14', '16', '18', '22', '31', '33', '44', '47', '55', '63', '77', '99']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 19 - São Paulo Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '11', '16', '55', '10', '31', '14', '4', '5', '7', '63', '99', '22', '6', '9', '47', '3', '18']
core           INFO 	Loading data for Qatar Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/20/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/20/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '10', '14', '4', '55', '22', '31', '5', '11', '18', '16', '3', '63', '7', '6', '99', '47', '9']
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2021 - Round 20 - Qatar Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '10', '14', '4', '77', '55', '33', '22', '31', '5', '11', '18', '16', '3', '63', '7', '6', '99', '47', '9']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2021 - Round 21 - Saudi Arabian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '22', '10', '77', '16', '55', '31', '4', '14', '99', '7', '3', '18', '63', '5', '6', '47', '9']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2021/21/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2021/21/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '31', '3', '10', '16', '55', '99', '4', '18', '6', '14', '22', '7', '5', '11', '9', '63', '47']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2021 - Round 22 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '11', '4', '22', '10', '55', '3', '16', '18', '31', '7', '99', '14', '5', '63', '6', '47', '9']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['33', '44', '4', '11', '55', '77', '16', '22', '31', '3', '14', '10', '18', '99', '5', '6', '63', '7', '47']

Processing 2022 - Round 1 - Bahrain Grand Prix

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/1/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/1/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '77', '20', '14', '63', '10', '31', '47', '4', '23', '24', '22', '27', '3', '18', '6']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '77', '20', '14', '63', '10', '31', '47', '4', '23', '24', '22', '27', '3', '18', '6']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 2 - Saudi Arabian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2022/2/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/2/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '1', '31', '63', '14', '77', '10', '20', '4', '3', '24', '47', '18', '44', '23', '27', '6', '22']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/3/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/3/qualifying.json

Processing 2022 - Round 3 - Australian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '11', '4', '44', '63', '3', '31', '55', '14', '10', '77', '22', '24', '47', '23', '20', '5', '6', '18']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/3/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/3/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '5', '6', '10', '11', '14', '16', '18', '20', '22', '23', '24', '31', '44', '47', '55', '63', '77']

Processing 2022 - Round 4 - Emilia Romagna Grand Prix

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/4/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/4/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '1', '14', '5', '47', '55', '20', '23', '4', '22', '18', '3', '77', '44', '10', '63', '24', '6', '31']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 5 - Miami Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2022/5/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/5/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/6/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/6/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '63', '11', '44', '77', '20', '3', '47', '4', '31', '22', '10', '24', '5', '14', '18', '23', '6']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 6 - Spanish Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2022/6/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/6/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/7/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/7/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '11', '1', '4', '63', '14', '44', '5', '31', '22', '77', '20', '3', '47', '23', '10', '18', '6', '24']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 7 - Monaco Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2022/7/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/7/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '55', '1', '16', '63', '4', '14', '44', '77', '5', '10', '31', '3', '18', '6', '24', '22', '23', '47', '20']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '1', '55', '4', '3', '10', '63', '31', '5', '14', '44', '18', '24', '20', '22', '23', '47', '77', '6']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 8 - Azerbaijan Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '44', '10', '5', '14', '3', '4', '31', '77', '23', '22', '47', '6', '18', '20', '24', '16', '55']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2022 - Round 9 - Canadian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['14', '10', '5', '31', '3', '4', '63', '11', '1', '55', '77', '24', '18', '20', '44', '23', '22', '47', '6', '16']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/9/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/9/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '55', '44', '63', '16', '31', '77', '24', '14', '18', '3', '5', '23', '10', '4', '6', '20', '22', '47', '11']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/10/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/10/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '11', '44', '4', '14', '63', '24', '6', '10', '77', '22', '3', '31', '23', '20', '5', '47', '18']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 10 - British Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '11', '44', '4', '14', '63', '24', '6', '10', '77', '22', '3', '31', '23', '20', '5', '47', '18']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/11/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/11/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '63', '31', '20', '47', '14', '44', '10', '23', '77', '11', '22', '4', '3', '18', '24', '6', '5']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 11 - Austrian Grand Prix

logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '63', '11', '31', '20', '44', '47', '4', '3', '18', '24', '10', '23', '22', '6', '5', '14', '77']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/12/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/12/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '11', '44', '4', '63', '14', '22', '55', '20', '3', '31', '77', '5', '23', '10', '18', '24', '47', '6']
core           INFO 	Loading data for French Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 12 - French Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2022/12/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/12/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '14', '4', '31', '3', '18', '5', '10', '23', '77', '47', '24', '6', '20', '16', '22']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2022 - Round 13 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['6', '16', '23', '1', '63', '14', '55', '4', '5', '20', '44', '47', '31', '3', '18', '24', '22', '77', '10', '11']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/13/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/13/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '55', '11', '16', '4', '14', '31', '5', '18', '10', '24', '47', '3', '20', '23', '6', '22', '77']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 14 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '55', '11', '16', '31', '14', '44', '63', '23', '4', '3', '10', '24', '18', '47', '5', '6', '20', '22', '77']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '11', '14', '44', '63', '23', '3', '10', '18', '5', '6', '20', '77', '1', '16', '31', '4', '24', '47', '22']
core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/15/qualifying.json

Processing 2022 - Round 15 - Dutch Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '44', '11', '63', '4', '47', '22', '18', '10', '31', '14', '24', '23', '77', '3', '20', '5', '6']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/15/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/15/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '16', '44', '11', '14', '4', '55', '31', '18', '10', '23', '47', '5', '20', '24', '3', '6', '77', '22']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2022 - Round 16 - Italian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '55', '14', '4', '63', '22', '31', '44', '24', '10', '6', '45', '3', '77', '5', '20', '47', '18']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/16/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/16/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/17/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/17/qualifying.json

Processing 2022 - Round 17 - Singapore Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '11', '44', '55', '14', '4', '10', '1', '20', '22', '63', '18', '47', '5', '24', '77', '3', '31', '23', '6']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/17/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/17/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/18/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/18/qualifying.json

Processing 2022 - Round 18 - Japanese Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '31', '44', '14', '63', '5', '4', '3', '77', '22', '24', '47', '23', '10', '20', '18', '6']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '31', '44', '14', '63', '5', '4', '3', '77', '22', '24', '47', '23', '10', '20', '18', '6']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/19/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/19/qualifying.json

Processing 2022 - Round 19 - United States Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '16', '1', '11', '44', '63', '18', '4', '14', '77', '23', '5', '10', '24', '22', '20', '3', '31', '47', '6']
core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '1', '44', '63', '18', '4', '77', '23', '11', '5', '10', '16', '20', '14', '3', '47', '6', '24', '22', '31']
core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2022 - Round 20 - Mexico City Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '11', '55', '77', '16', '4', '14', '31', '3', '24', '22', '10', '20', '47', '5', '18', '23', '6']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/20/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/20/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '11', '63', '55', '16', '3', '31', '4', '77', '10', '23', '24', '5', '18', '47', '20', '6', '14', '22']
core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2022 - Round 21 - São Paulo Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '1', '55', '44', '63', '5', '47', '77', '10', '14', '23', '31', '18', '4', '20', '6', '24', '22', '3']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/21/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/21/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '14', '1', '11', '31', '77', '18', '5', '24', '47', '10', '23', '6', '22', '4', '20', '3']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)

Processing 2022 - Round 22 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '44', '63', '4', '16', '55', '3', '5', '23', '31', '14', '22', '77', '10', '18', '20', '47', '24', '6']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2022/22/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2022/22/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '55', '63', '4', '31', '18', '3', '5', '22', '24', '23', '10', '77', '47', '20', '44', '6', '14']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 1 - Bahrain Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/1/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/1/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 2 - Saudi Arabian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/2/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/2/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '14', '63', '55', '18', '31', '44', '81', '10', '27', '24', '20', '77', '1', '22', '23', '21', '4', '2']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/2/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/2/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 3 - Australian Grand Prix

req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '14', '55', '18', '16', '23', '10', '27', '31', '22', '4', '20', '21', '81', '24', '2', '77', '11']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '14', '55', '18', '16', '23', '10', '27', '31', '22', '4', '20', '21', '81', '24', '2', '77', '11']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/5/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/5/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '14', '55', '20', '10', '63', '16', '31', '1', '77', '23', '27', '44', '24', '21', '4', '22', '18', '81', '2']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 5 - Miami Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/5/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/5/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/6/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/6/qualifying.json

Processing 2023 - Round 6 - Monaco Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '16', '31', '55', '44', '10', '63', '22', '4', '81', '21', '23', '18', '77', '2', '20', '27', '24', '11']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/6/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/6/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/7/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/7/qualifying.json

Processing 2023 - Round 7 - Spanish Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '55', '4', '10', '44', '18', '31', '27', '14', '81', '11', '63', '24', '21', '22', '77', '20', '23', '16', '2']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/7/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/7/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 8 - Canadian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/8/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/8/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '27', '14', '44', '63', '31', '4', '55', '81', '23', '16', '11', '18', '20', '77', '22', '10', '21', '2', '24']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/10/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/10/qualifying.json

Processing 2023 - Round 10 - British Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '55', '63', '44', '23', '14', '10', '27', '18', '31', '2', '77', '11', '22', '24', '21', '20']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/10/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/10/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/11/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/11/qualifying.json

Processing 2023 - Round 11 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '24', '16', '77', '14', '11', '27', '55', '31', '3', '18', '10', '23', '22', '63', '20', '2']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/11/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/11/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']
core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 13 - Dutch Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/13/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/13/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '23', '14', '55', '11', '81', '16', '2', '18', '10', '44', '22', '27', '24', '31', '20', '77', '40']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/13/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/13/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 14 - Italian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/14/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/14/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '63', '11', '23', '81', '44', '4', '14', '22', '40', '27', '77', '2', '24', '10', '31', '20', '18']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/14/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/14/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 15 - Singapore Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/15/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '63', '16', '4', '44', '20', '14', '31', '27', '40', '1', '10', '11', '23', '22', '77', '81', '2', '24', '18']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/15/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/15/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 16 - Japanese Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/16/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/16/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '11', '55', '44', '63', '22', '14', '40', '10', '23', '31', '20', '77', '18', '27', '24', '2']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']
core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 19 - Mexico City Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/19/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/19/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '3', '11', '44', '81', '63', '77', '24', '10', '27', '14', '23', '22', '31', '20', '18', '4', '2']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/19/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/19/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']
core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/21/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/21/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '63', '10', '23', '2', '77', '20', '14', '44', '11', '27', '18', '3', '4', '31', '24', '81', '22']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2023 - Round 21 - Las Vegas Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2023/21/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/21/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/22/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/22/qualifying.json

Processing 2023 - Round 22 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '4', '22', '14', '27', '11', '10', '44', '31', '18', '23', '3', '55', '20', '77', '24', '2']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2023/22/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2023/22/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 1 - Bahrain Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/1/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/1/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/1/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/1/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 2 - Saudi Arabian Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/2/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/2/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '14', '81', '4', '63', '44', '22', '18', '38', '23', '20', '3', '27', '77', '31', '10', '2', '24']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/3/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/3/qualifying.json

Processing 2024 - Round 3 - Australian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['1', '55', '11', '4', '16', '81', '63', '22', '18', '14', '44', '23', '77', '20', '31', '27', '10', '3', '24']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/3/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/3/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/4/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/4/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '55', '14', '81', '44', '16', '63', '22', '3', '27', '77', '23', '31', '18', '10', '20', '2', '24']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 4 - Japanese Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/4/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/4/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/7/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/7/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '55', '63', '22', '44', '3', '27', '11', '31', '18', '23', '10', '77', '24', '20', '14', '2']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 7 - Emilia Romagna Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/7/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/7/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/8/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/8/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '31', '3', '18', '27', '14', '2', '20', '11', '77', '24']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 8 - Monaco Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/8/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/8/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/9/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/9/qualifying.json

Processing 2024 - Round 9 - Canadian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '3', '14', '44', '22', '18', '23', '16', '55', '2', '20', '10', '11', '77', '31', '27', '24']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/9/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/9/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/10/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/10/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '16', '55', '10', '11', '31', '81', '14', '77', '27', '18', '24', '20', '22', '3', '23', '2']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 10 - Spanish Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/12/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/12/qualifying.json

Processing 2024 - Round 12 - British Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '4', '1', '81', '27', '55', '18', '23', '14', '16', '2', '22', '24', '3', '77', '20', '31', '11', '10']
core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/12/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/12/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/13/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/13/qualifying.json

Processing 2024 - Round 13 - Hungarian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '55', '44', '16', '14', '18', '3', '22', '27', '77', '23', '2', '20', '11', '63', '24', '31', '10']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/13/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/13/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/14/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/14/qualifying.json

Processing 2024 - Round 14 - Belgian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '44', '4', '81', '63', '55', '14', '31', '23', '10', '3', '77', '18', '27', '20', '22', '2', '24']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/14/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/14/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']
core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/15/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/15/qualifying.json

Processing 2024 - Round 15 - Dutch Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '11', '16', '14', '18', '10', '55', '23', '44', '22', '27', '20', '3', '31', '77', '24', '2']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/15/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/15/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/16/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/16/qualifying.json

Processing 2024 - Round 16 - Italian Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/16/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/16/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/17/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/17/qualifying.json

Processing 2024 - Round 17 - Azerbaijan Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '11', '63', '1', '44', '14', '43', '23', '50', '22', '27', '18', '3', '10', '4', '77', '24', '31']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/17/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/17/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 18 - Singapore Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '81', '27', '14', '22', '16', '55', '23', '43', '11', '20', '31', '3', '18', '10', '77', '24']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/18/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/18/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']
core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Processing 2024 - Round 20 - Mexico City Grand Prix

Request for URL https://api.jolpi.ca/ergast/f1/2024/20/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/20/qualifying.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '1', '4', '16', '63', '44', '20', '10', '23', '27', '22', '30', '14', '18', '77', '43', '81', '11', '31', '24']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/20/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/20/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']
core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/22/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/22/qualifying.json

Processing 2024 - Round 22 - Las Vegas Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '55', '10', '16', '1', '4', '22', '81', '27', '44', '31', '20', '24', '43', '30', '11', '14', '23', '77', '18']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/22/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/22/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/24/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/24/qualifying.json

Processing 2024 - Round 24 - Abu Dhabi Grand Prix

req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '55', '27', '1', '10', '63', '14', '77', '11', '22', '30', '18', '16', '20', '23', '24', '44', '43', '61']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2024/24/results.json failed; using cached response
Traceback (most recent call last):
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests_cache/session.py", line 297, in _resend
    response.raise_for_status()
  File "/Users/minaheelkhan/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.jolpi.ca/ergast/f1/2024/24/results.json
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

Final dataset shape: (2738, 18)

,DriverNumber,Abbreviation,FullName,TeamName,QualiPos,Q1,Q2,Q3,QualiTime,RacePos,StartPos,Status,Year,Round,EventName,Era,CircuitType,Outcome
0,44,HAM,Lewis Hamilton,Mercedes,1.0,0 days 00:01:22.824000,0 days 00:01:22.051000,0 days 00:01:21.164000,0 days 00:01:21.164000,2.0,1.0,Finished,2018,1,Australian Grand Prix,Pre-2022,Street,Podium
1,7,RAI,Kimi Räikkönen,Ferrari,2.0,0 days 00:01:23.096000,0 days 00:01:22.507000,0 days 00:01:21.828000,0 days 00:01:21.828000,3.0,2.0,Finished,2018,1,Australian Grand Prix,Pre-2022,Street,Podium
2,5,VET,Sebastian Vettel,Ferrari,3.0,0 days 00:01:23.348000,0 days 00:01:21.944000,0 days 00:01:21.838000,0 days 00:01:21.838000,1.0,3.0,Finished,2018,1,Australian Grand Prix,Pre-2022,Street,Podium
3,33,VER,Max Verstappen,Red Bull Racing,4.0,0 days 00:01:23.483000,0 days 00:01:22.416000,0 days 00:01:21.879000,0 days 00:01:21.879000,6.0,4.0,Finished,2018,1,Australian Grand Prix,Pre-2022,Street,Points
4,3,RIC,Daniel Ricciardo,Red Bull Racing,5.0,0 days 00:01:23.494000,0 days 00:01:22.897000,0 days 00:01:22.152000,0 days 00:01:22.152000,4.0,8.0,Finished,2018,1,Australian Grand Prix,Pre-2022,Street,Points

2c. Data Cleaning and Validation Checks

Before proceeding to EDA and modelling, I verify:

No duplicate keys

Outcome distribution is sensible

Race positions fall within expected range

🔍 Check for Duplicate Driver-Event Rows

In [10]:
duplicate_check = event_driver_df.duplicated(
    subset=["Year", "Round", "Abbreviation"]
).sum()

print("Duplicate rows:", duplicate_check)

Duplicate rows: 0

📊 Inspect Outcome Distribution

In [11]:
event_driver_df["Outcome"].value_counts()

NoPoints    200
Points      140
Podium       60
Name: Outcome, dtype: int64

🏎️ Inspect Basic Statistics

In [12]:
event_driver_df[["QualiPos", "RacePos", "StartPos"]].describe()

         QualiPos     RacePos    StartPos
count  400.000000  400.000000  400.000000
mean    10.500000   10.500000   10.450000
std      5.773503    5.773503    5.777625
min      1.000000    1.000000    0.000000
25%      5.750000    5.750000    5.000000
50%     10.500000   10.500000   10.000000
75%     15.250000   15.250000   15.000000
max     20.000000   20.000000   20.000000

2d. Save Dataset for Reproducibility

Saving the dataset ensures:

Results can be replicated without re-downloading

The R time-series analysis can import the same clean data

In [ ]:
event_driver_df.to_csv("event_driver_df.csv", index=False)

print("Dataset saved as event_driver_df.csv")

In [28]:
event_driver_df["Year"].value_counts().sort_index()

2018    420
2019    420
2020    340
2021    439
2022    440
2023    320
2024    359
Name: Year, dtype: int64

# after second run through 
2018    420
2019    420
2020    340
2021    439
2022    439
Name: Year, dtype: int64

# after third run through
2018    420
2019    420
2020    340
2021    439
2022    439
2023    320
2024    359
Name: Year, dtype: int64

# same after fourth run through so yay done